
package com.example.filedataprocessingclient.soapservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "SoapServicePortService", targetNamespace = "http://example.com/service", wsdlLocation = "http://localhost:8080/ws/soapservice.wsdl")
public class SoapServicePortService
    extends Service
{

    private final static URL SOAPSERVICEPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPSERVICEPORTSERVICE_EXCEPTION;
    private final static QName SOAPSERVICEPORTSERVICE_QNAME = new QName("http://example.com/service", "SoapServicePortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/soapservice.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPSERVICEPORTSERVICE_WSDL_LOCATION = url;
        SOAPSERVICEPORTSERVICE_EXCEPTION = e;
    }

    public SoapServicePortService() {
        super(__getWsdlLocation(), SOAPSERVICEPORTSERVICE_QNAME);
    }

    public SoapServicePortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPSERVICEPORTSERVICE_QNAME, features);
    }

    public SoapServicePortService(URL wsdlLocation) {
        super(wsdlLocation, SOAPSERVICEPORTSERVICE_QNAME);
    }

    public SoapServicePortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPSERVICEPORTSERVICE_QNAME, features);
    }

    public SoapServicePortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapServicePortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapServicePort
     */
    @WebEndpoint(name = "SoapServicePortSoap11")
    public SoapServicePort getSoapServicePortSoap11() {
        return super.getPort(new QName("http://example.com/service", "SoapServicePortSoap11"), SoapServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapServicePort
     */
    @WebEndpoint(name = "SoapServicePortSoap11")
    public SoapServicePort getSoapServicePortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.com/service", "SoapServicePortSoap11"), SoapServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPSERVICEPORTSERVICE_EXCEPTION!= null) {
            throw SOAPSERVICEPORTSERVICE_EXCEPTION;
        }
        return SOAPSERVICEPORTSERVICE_WSDL_LOCATION;
    }

}
