
package com.example.filedataprocessingclient.soapservice;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "SoapServicePort", targetNamespace = "http://example.com/service")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapServicePort {


    /**
     * 
     * @param getProportionLaptopsCountRequest
     * @return
     *     returns com.example.filedataprocessingclient.consumingwebservice.wsdl.GetProportionLaptopsCountResponse
     */
    @WebMethod
    @WebResult(name = "getProportionLaptopsCountResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getProportionLaptopsCountResponse")
    public GetProportionLaptopsCountResponse getProportionLaptopsCount(
        @WebParam(name = "getProportionLaptopsCountRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getProportionLaptopsCountRequest")
        GetProportionLaptopsCountRequest getProportionLaptopsCountRequest);

    /**
     * 
     * @param getProducerLaptopCountRequest
     * @return
     *     returns com.example.filedataprocessingclient.consumingwebservice.wsdl.GetProducerLaptopCountResponse
     */
    @WebMethod
    @WebResult(name = "getProducerLaptopCountResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getProducerLaptopCountResponse")
    public GetProducerLaptopCountResponse getProducerLaptopCount(
        @WebParam(name = "getProducerLaptopCountRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getProducerLaptopCountRequest")
        GetProducerLaptopCountRequest getProducerLaptopCountRequest);

}
