INSERT INTO laptop
(manufacturer,
 screen_size,
 screen_type,
 screen_resolution,
 has_touch_screen,
 processor_name,
 physical_cores_num,
 clock_speed,
 ram_size,
 disc_storage_size,
 disc_type,
 graphic_card_name,
 graphic_card_memory,
 os_name,
 disc_reader)
values
('Samsung',
 '21',
 'Matowy',
 '1920x1080',
 'tak',
 'intel core i5',
 '8',
 '3GHz',
 '16GB',
 '1TB',
 'SSD',
 'Nvidia Gforce',
 '4GB',
 'Windows',
 'CD/DVD');
INSERT INTO laptop
(manufacturer,
 screen_size,
 screen_type,
 screen_resolution,
 has_touch_screen,
 processor_name,
 physical_cores_num,
 clock_speed,
 ram_size,
 disc_storage_size,
 disc_type,
 graphic_card_name,
 graphic_card_memory,
 os_name,
 disc_reader)
values
    ('Asus',
     '21',
     'Antyrefleksyjny',
     '1920x1080',
     'nie',
     'intel core i7',
     '8',
     '3GHz',
     '16GB',
     '1TB',
     'SSD',
     'Nvidia Gforce',
     '4GB',
     'Windows',
     'CD/DVD');